# Generated by Django 2.2.6 on 2019-10-08 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ice_cream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=200)),
                ('base', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Chocolate', 'Chocolate')], max_length=200)),
                ('available', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Seasonal', 'Seasonal')], max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('date_churned', models.DateField(default=datetime.date.today, verbose_name='Date Churned')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
