# Generated by Django 2.2.6 on 2019-10-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ice_cream',
            new_name='IceCream',
        ),
    ]
